export const modelPicturesMap = {
    "Tous": "",
    "Acticycle": "images/Acticycle.png",
    "BIRO": "images/BIRO.png",
    "Cyclospace": "images/Cyclospace.jpg",
    "Formidable": "images/Formidable.png",
    "Frikar": "images/Frikar.png",
    "Karbikes": "images/Karbikes.jpg",
    "Urbaner": "images/Urbaner.jpeg",
    "WEEZ": "images/WEEZ.png",
    "Woodybus": "images/Woodybus.png",
    "MidiPile": "images/Midipile.png",
    "Maillon Mobility": "images/MaillonMobility.jpg",
    "Qbx": "images/Qbx.jpg",
    "La Bagnole": "images/LaBagnole.png",
    "Vehlio": "images/Vehlio.jpg",
}

export const locations = [
    "Tous",
    "Avant Pays Savoyard",
    "CA du Grand Avignon",
    "Centre Hospitalier de Niort",
    "CC 7 Vallées",
    "CC Briançon",
    "CC Clunisois",
    "CC Grand Pic St Loup",
    "Commune de Tressin",
    "Commune des Mureaux",
    "Commune du Teil",
    "La Chapelle-Thouarault",
    "Lalouvesc",
    "Le Mans",
    "Loos en Gohelle",
    "PNR Grand Causses",
    "Toulouse"
]
