export const modelPicturesMap = {
    "Tous": "",
    "Acticycle": "images/Acticycle.png",
    "BIRO": "images/BIRO.png",
    "Biro": "images/BIRO.png",
    "Cyclospace": "images/Cyclospace.jpg",
    "Formidable": "images/Formidable.png",
    "Galian": "images/Formidable.png",
    "Frikar": "images/Frikar.png",
    "Podbike": "images/Frikar.png",
    "Karbikes": "images/Karbikes.jpg",
    "Urbaner": "images/Urbaner.jpeg",
    "WEEZ": "images/WEEZ.png",
    "Weez": "images/WEEZ.png",
    "Woodybus": "images/Woodybus.png",
    "Midipile": "images/Midipile.png",
    "Maillon Mobility": "images/MaillonMobility.jpg",
    "Daily": "images/MaillonMobility.jpg",
    "Sorean": "images/Qbx.jpg",
    "La Bagnole": "images/LaBagnole.png",
    "LA BAGNOLE": "images/LaBagnole.png",
    "Vhelio": "images/Vhelio.jpg",
    "AMI": "images/AMI.png",
    "Citroën AMI": "images/AMI.png",
    "Speedbike": "images/Speedbike.jpg",
    "Galibot": "images/Galibot.png",
    "BOB": "images/Bob_sanka_cycle.jpg",
}

export const locations = [
    "Tous",
    "Avant Pays Savoyard",
    "CA du Grand Avignon",
    "CC 7 Vallées",
    "CC Briançon",
    "CC Clunisois",
    "CC de Puisayes Forterre",
    "CC Grand Pic St Loup",
    "Centre Hospitalier de Niort",
    "Commune de Tressin",
    "Commune des Mureaux",
    "Commune du Teil",
    "La Chapelle-Thouarault",
    "Lalouvesc",
    "Le Mans",
    "Loos en Gohelle",
    "Loos les Lilles",
    "PETR Sud Lozère",
    "PNR Grand Causses",
    "Toulouse"
]

export const wikiLinks = {
    "Avant Pays Savoyard": "https://wikixd.fabmob.io/wiki/Avant-pays_savoyard",
    "CA du Grand Avignon": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_d%27Agglom%C3%A9ration_du_Grand_Avignon",
    "Centre Hospitalier de Niort": "https://wikixd.fabmob.io/wiki/Centre_Hospitalier_de_Niort",
    "CC 7 Vallées": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_de_communes_des_7_Vall%C3%A9es",
    "CC Briançon": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_de_Communes_du_Brian%C3%A7onnais",
    "CC Clunisois": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_de_communes_du_Clunisois",
    "CC Grand Pic St Loup": "https://wikixd.fabmob.io/wiki/CC_Grand_Pic_Saint_Loup",
    "Commune de Tressin": "https://wikixd.fabmob.io/wiki/Tressin",
    "Commune des Mureaux": "https://wikixd.fabmob.io/wiki/Commune_Les_Mureaux",
    "Commune du Teil": "https://wikixd.fabmob.io/wiki/Commune_Le_Teil",
    "La Chapelle-Thouarault": "https://wikixd.fabmob.io/wiki/Commune_la_Chapelle-Thouarault",
    "Lalouvesc": "https://wikixd.fabmob.io/wiki/Commune_de_Lalouvesc",
    "Le Mans": "https://wikixd.fabmob.io/wiki/Le_Mans_M%C3%A9tropole",
    "Loos en Gohelle": "https://wikixd.fabmob.io/wiki/Ville_de_Loos-en-Gohelle",
    "PNR Grand Causses": "https://wikixd.fabmob.io/wiki/PNR_des_Grands_Causses",
    "Toulouse": "https://wikixd.fabmob.io/wiki/INSA",
    "PETR Sud Lozère": "https://wikixd.fabmob.io/wiki/V%C3%A9lis_dans_le_PETR_Loz%C3%A8re"
}
