export const modelPicturesMap = {
    "Tous": "",
    "Acticycle": "images/Acticycle.png",
    "BIRO": "images/BIRO.png",
    "Cyclospace": "images/Cyclospace.jpg",
    "Formidable": "images/Formidable.png",
    "Frikar": "images/Frikar.png",
    "Karbikes": "images/Karbikes.jpg",
    "Urbaner": "images/Urbaner.jpeg",
    "WEEZ": "images/WEEZ.png",
    "Woodybus": "images/Woodybus.png",
    "MidiPile": "images/Midipile.png",
    "Maillon Mobility": "images/MaillonMobility.jpg",
    "Qbx": "images/Qbx.jpg",
    "La Bagnole": "images/LaBagnole.png",
    "Vhelio": "images/Vhelio.jpg",
}

export const locations = [
    "Tous",
    "Avant Pays Savoyard",
    "CA du Grand Avignon",
    "Centre Hospitalier de Niort",
    "CC 7 Vallées",
    "CC Briançon",
    "CC Clunisois",
    "CC Grand Pic St Loup",
    "Commune de Tressin",
    "Commune des Mureaux",
    "Commune du Teil",
    "La Chapelle-Thouarault",
    "Lalouvesc",
    "Le Mans",
    "Loos en Gohelle",
    "PNR Grand Causses",
    "Toulouse"
]

export const wikiLinks = {
    "Avant Pays Savoyard": "https://wikixd.fabmob.io/wiki/Avant-pays_savoyard",
    "CA du Grand Avignon": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_d%27Agglom%C3%A9ration_du_Grand_Avignon",
    "Centre Hospitalier de Niort": "https://wikixd.fabmob.io/wiki/Centre_Hospitalier_de_Niort",
    "CC 7 Vallées": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_de_communes_des_7_Vall%C3%A9es",
    "CC Briançon": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_de_Communes_du_Brian%C3%A7onnais",
    "CC Clunisois": "https://wikixd.fabmob.io/wiki/Communaut%C3%A9_de_communes_du_Clunisois",
    "CC Grand Pic St Loup": "https://wikixd.fabmob.io/wiki/CC_Grand_Pic_Saint_Loup",
    "Commune de Tressin": "https://wikixd.fabmob.io/wiki/Tressin",
    "Commune des Mureaux": "https://wikixd.fabmob.io/wiki/Commune_Les_Mureaux",
    "Commune du Teil": "https://wikixd.fabmob.io/wiki/Commune_Le_Teil",
    "La Chapelle-Thouarault": "https://wikixd.fabmob.io/wiki/Commune_la_Chapelle-Thouarault",
    "Lalouvesc": "https://wikixd.fabmob.io/wiki/Commune_de_Lalouvesc",
    "Le Mans": "https://wikixd.fabmob.io/wiki/Le_Mans_M%C3%A9tropole",
    "Loos en Gohelle": "https://wikixd.fabmob.io/wiki/Ville_de_Loos-en-Gohelle",
    "PNR Grand Causses": "https://wikixd.fabmob.io/wiki/PNR_des_Grands_Causses",
    "Toulouse": "https://wikixd.fabmob.io/wiki/INSA"
}

export const VELIS = [
    {name: "Acticycle 1", licencePlate: "ACTI0001"},
    {name: "Acticycle 2", licencePlate: "ACTI0002"},
    {name: "Acticycle 3", licencePlate: "ACTI0003"},
    {name: "BIRO 1", licencePlate: "GB418VP"},
    {name: "BIRO 2", licencePlate: "GD483SR"},
    {name: "BIRO 3", licencePlate: "GD740SR"},
    {name: "BIRO 4", licencePlate: "GD785SR"},
    {name: "BIRO 5", licencePlate: "GD946SR"},
    {name: "BIRO 6", licencePlate: "GG149XZ"},
    {name: "BIRO 7", licencePlate: "GP243HH"},
    {name: "Cyclospace", licencePlate: "STC20"},
    {name: "Formidable", licencePlate: "GALFORMI01"},
    {name: "Frikar", licencePlate: "FRIKAR01"},
    {name: "Karbikes 1", licencePlate: "KARBIKES01"},
    {name: "Karbikes 2", licencePlate: "KARBIKES02"},
    {name: "Karbikes 3", licencePlate: "KARBIKES03"},
    {name: "La Bagnole", licencePlate: "GY831PD"},
    {name: "Maillon Mobility 1", licencePlate: "MAIL0001"},
    {name: "Maillon Mobility 2", licencePlate: "MAIL0002"},
    {name: "Maillon Mobility 3", licencePlate: "MAIL0003"},
    {name: "Urbaner 1", licencePlate: "BY2F7TH5EH"},
    {name: "Urbaner 2", licencePlate: "BY32ZZZ698"},
    {name: "Urbaner 3", licencePlate: "BY7C8XZDFD"},
    {name: "Urbaner 4", licencePlate: "BYC8AADHFC"},
    {name: "Urbaner 5", licencePlate: "BYZD9TVA4C"},
    {name: "Urbaner 6", licencePlate: "BYZE2PK7E6"},
    {name: "Urbaner 7", licencePlate: "URBANERINSALAAS"},
    {name: "Vhelio", licencePlate: "VHELIOINSALAAS"},
    {name: "WEEZ 1", licencePlate: "GE800QY"},
    {name: "WEEZ 2", licencePlate: "GJ756XR"},
    {name: "WEEZ 3", licencePlate: "GP065PN"},
    {name: "WEEZ 4", licencePlate: "GV046CN"},
    {name: "WEEZ 5", licencePlate: "GV136CN"},
    {name: "WEEZ 6", licencePlate: "GV194CN"},
    {name: "Woodybus", licencePlate: "BCF2CBFBBC"},
]
