import pandas as pd
import numpy as np
import datetime
from zoneinfo import ZoneInfo
import os

'''
This file contains methods to process the raw data from various questionnaires sent to users.

Most of the methods are used to clean survey data, fixing typos and inconsistencies.

After cleanup, the survey replies are also matched to GPS trip data generated by the process_gps_data.py script.
    Matching is done by comparing declared location, vehicule type and date of the trip to the extracted trip data.
    A large margin of error is allowed, since trip detection is not perfect, and respondants aren't always accurate in dating their trips.

Sources:
    SURVEY_SOURCES_FOLDER/Carnetdebord-[...].xlsx : excel file containing answers to the "Carnet de bord" questionnaire (filled after each trip)
    SURVEY_SOURCES_FOLDER/CarnetdebordPRO[...].xlsx : excel file containing answers to the "Carnet de bord" questionnaire (filled after each professional trip)
    SURVEY_SOURCES_FOLDER/Retourd[...].xlsx : excel file containing answers to the tourism questionnaire (filled after each tourism tryout)
    SURVEY_SOURCES_FOLDER/Questionnaire1[...].xlsx : excel file containing answers to the initial questionnaire (filled before the experiment starts)
    SURVEY_SOURCES_FOLDER/Le_Mans_Carnet de bord PRO.xlsx : excel file containing answers to a "Carnet de bord" questionnaire specific to Le Mans
    ../carnet_niort_formated.csv : csv file containing answers to a "Carnet de bord" questionnaire specific to Niort Hospital

Param:
    df_trips : dataframe containing trip data, with one row per trip. It was generated using the process_gps_data.py script.
        It contains the following columns:
            'UniqueTripID', 'coords', 'timestamps', 'TotalDistanceKm', 'AvgSpeed',
            'StartTime', 'EndTime', 'Licence plate', 'VIN', 'vehicle ID', 'Brand',
            'Model', 'Category', 'External temperature (°C)', 'T° Sensor 1',
            'Prev datetime', 'DurationSinceLast', 'location'

Returns:
    trips_with_carnet_match : df_trips dataframe extended with information extracted from the surveys.
        One row still corresponds to one trip, with the exception of survey results that could not be matched. 
        In that case, the new columns corresponding to survey results are filled, and trip columns are set to None.
        When a match is found, both the trip and the survey columns are filled.
        Columns added to the existing df_trips columns (subset of used columns, the dataframe includes every column from the original survey files):
            "carnetEntryIndex", "date_questionnaire", "territoire", "nom", "prenom", "vehicule", 
            "date", "heure_debut", "heure_fin", "duree", "moment", 
            "meteo_ensoleille", "meteo_nuageux", "meteo_pluvieux", "meteo_venteux", "meteo_neigeux", "meteo_brouillard", "meteo_autre", 
            "depart", "arrivee", "etape", "distance", "passagers", 
            "avantage_aucun", "avantage_agilite", "avantage_confort", "avantage_observation", "avantage_fierté", "avantage_reactions", "avantage_bien_etre", "avantage_autre", 
            "difficulte_aucune", "difficulte_visibilite", "difficulte_amenagement", "difficulte_stationnement", "difficulte_vehicule", "difficulte_comportement", "difficulte_autre", "difficultes_details"
            "point_noir_1", "point_noir_2", "bilan", "commentaires", 
            "tourisme_avantages_detail", "tourisme_difficulte_trafic", "tourisme_difficulte_meteo", "tourisme_difficulte_denivele", 
            "tourisme_difficulte_distance", "tourisme_difficulte_autonomie", "tourisme_difficulte_diff_vitesse", "tourisme_difficulte_positionnement", 
            "tourisme_difficulte_intersection", "tourisme_difficulte_depart_cote", "tourisme_difficulte_fatigue", "tourisme_difficulte_depassement", 
            "tourisme_difficulte_autre", "tourisme_difficulte_detail",
            "start_time", "end_time", "prenom_lower", "nom_lower", "mode_domicile_travail", "mode_domicile_etudes", "mode_domicile_loisirs", 
            "point_noir_1_lon", "point_noir_1_lat", 
'''
SURVEY_SOURCES_FOLDER = "survey_sources"

# Load 'filename' excel file into a dataframe and rename columns to usable names.
# Source file is an export of answers to a questionnaire sent to users in the tourism use case.
def process_tourisme_file(filename):
    df_tourisme = pd.read_excel(filename, dtype={"Date": str, "10: Date du déplacement": str})
    df_tourisme.rename(columns={
        "Date": "date_questionnaire",
        "1: Votre territoire d'expérimentation :": "territoire",
        "2: Votre nom": "nom",
        "1: Votre prénom": "prenom",
        "9: Quel véhicule avez-vous testé ?": "vehicule",
        "10: Date du déplacement": "date",
        "11: L'heure de début du déplacement (environ - Exemple de saisie acceptée  10:30) : ": "heure_debut",
        "12: L'heure de fin d'utilisation du véhicule (environ - Exemple de saisie acceptée  10:30) : ": "heure_fin",
        "15: Ensoleillé": "meteo_ensoleille",
        "15: Nuageux": "meteo_nuageux",
        "15: Pluvieux": "meteo_pluvieux",
        "15: Venteux": "meteo_venteux",
        "15: Neigeux": "meteo_neigeux",
        "15: Brouillard": "meteo_brouillard",
        "15: Autre": "meteo_autre",
        "13: Estimation du nombre de km parcourus dans le trajet": "distance",
        "14: Nombre de passagers total (conducteur inclus)": "passagers",
        "16: Aucun": "avantage_aucun",
        "16: Sentiment de vitesse agréable et d'agilité à se déplacer": "avantage_agilite",
        "16: Confort du véhicule ": "avantage_confort",
        "16: Observation du paysage et des alentours": "avantage_observation",
        "16: Sentiment de fierté": "avantage_fierté",
        "16: Réactions positives des autres usagers vis à vis du véhicule ": "avantage_reactions",
        "16: Bien être physique ": "avantage_bien_etre",
        "16: Autre": "avantage_autre",
        '17: Par rapport à la question précédente, pouvez-vous expliquer ces réponses ? (5 lignes maximum)': "tourisme_avantages_detail",
        '24: Trafic routier élevé': "tourisme_difficulte_trafic",
        '24: Conditions météo dégradées': "tourisme_difficulte_meteo",
        '24: Profils de routes difficiles (trop de dénivelé)': "tourisme_difficulte_denivele",
        '24: Distances à parcourir trop longues': "tourisme_difficulte_distance",
        '24: Autonomie batterie insuffisante': "tourisme_difficulte_autonomie",
        '24: Différentiel de vitesses trop important avec certains véhicules': "tourisme_difficulte_diff_vitesse",
        '24: Positionnement sur la route (sur la chaussée, sur bas-côté, …)': "tourisme_difficulte_positionnement",
        '24: Les intersections (redémarrage, visibilité)': "tourisme_difficulte_intersection",
        '24: Les démarrages en côte ': "tourisme_difficulte_depart_cote",
        '24: Fatigue physique': "tourisme_difficulte_fatigue",
        '24: Dépassement d’autres véhicules': "tourisme_difficulte_depassement",
        '24: Autre': "tourisme_difficulte_autre",
        "26: Avez-vous rencontré des soucis techniques ? Expliquez, racontez (5 lignes max) :": "tourisme_difficulte_detail",
        "35: D’autres éléments a nous partager ? " : "commentaires",
    }, inplace=True)

    df_tourisme["territoire"] = "CA du Grand Avignon"

    df_tourisme["bilan"] = np.where(df_tourisme["34: Très positif"] == 1, "Très positif", 
        np.where(df_tourisme["34: Négatif"] == 1, "Négatif", 
        np.where(df_tourisme["34: Positif"] == 1, "Positif", 
        np.where(df_tourisme["34: Très négatif"] == 1, "Très négatif", "")))
    )

    def fix_distance_tourisme(distance):
        if ":" in distance:
            distance = distance.split(":")[0]
        if "km" in distance:
            distance = distance.split("km")[0]
        return distance

    df_tourisme["distance"] = df_tourisme["distance"].apply(fix_distance_tourisme)
    df_tourisme.drop(list(df_tourisme.filter(regex = ':')), axis = 1, inplace = True)
    return df_tourisme

# Load 'filename' excel file into a dataframe and rename columns to usable names.
# Source file is an export of answers to the "Carnet de bord" questionnaire (filled after each trip)
def process_carnet_file(filename):
    df = pd.read_excel(filename, dtype={"Date": str, "6: La date du déplacement :": str})
    df.rename(columns={
        "Date": "date_questionnaire",
        "1: Votre territoire d'expérimentation :": "territoire",
        "3: Votre NOM": "nom",
        "4: Votre prénom": "prenom",
        "5: Quel véhicule avez-vous utilisé ? ": "vehicule",
        "6: La date du déplacement :": "date",
        "7: L'heure de début d'utilisation du véhicule (environ) :": "heure_debut",
        "8: L'heure de fin d'utilisation du véhicule (environ) : ": "heure_fin",
        "9: Durée du déplacement (en minutes)": "duree",
        "10: Moment de la journée :": "moment",
        "11: Ensoleillé ": "meteo_ensoleille",
        "11: Nuageux": "meteo_nuageux",
        "11: Pluvieux": "meteo_pluvieux",
        "11: Venteux": "meteo_venteux",
        "11: Neigeux": "meteo_neigeux",
        "11: Brouillard": "meteo_brouillard",
        "11: Autre": "meteo_autre",
        "12.1: Point de départ et d'arrivée de votre déplacement :: Départ :": "depart",
        "12.2: Point de départ et d'arrivée de votre déplacement :: Arrivée :": "arrivee",
        "12.3: Point de départ et d'arrivée de votre déplacement :: Point d'étape (facultatif) :": "etape",
        "13: Estimation du nombre total de km parcourus dans le trajet": "distance",
        "14: Nombre de passagers total (conducteur inclus)": "passagers",
        "15: Motif du trajet": "motif",
        "17: Aucun": "avantage_aucun",
        "17: Sentiment de vitesse agréable et d'agilité à se déplacer": "avantage_agilite",
        "17: Confort du véhicule ": "avantage_confort",
        "17: Observation du paysage et des alentours": "avantage_observation",
        "17: Sentiment de fierté": "avantage_fierté",
        "17: Réactions positives des autres usagers vis à vis du véhicule ": "avantage_reactions",
        "17: Bien être physique ": "avantage_bien_etre",
        "17: Autre": "avantage_autre",
        "18: Aucune ": "difficulte_aucune",
        "18: Visibilité réduite": "difficulte_visibilite",
        "18: Aménagements": "difficulte_amenagement",
        "18: Stationnement": "difficulte_stationnement",
        "18: Problèmes avec le véhicule": "difficulte_vehicule",
        "18: Comportement des autres usagers de la route": "difficulte_comportement",
        "18: Autre": "difficulte_autre",
        "19.1: Pourriez-vous indiquer deux points sur votre trajet où vous aviez rencontré ces difficultés ? (donner l'adresse): Point noir 1 :": "point_noir_1",
        "19.2: Pourriez-vous indiquer deux points sur votre trajet où vous aviez rencontré ces difficultés ? (donner l'adresse): Point noir 2 : ": "point_noir_2",
        "20: Si nécessaire, pourriez-vous décrire les difficultés rencontrées dans les points noirs identifiés dans la question précédente ?": "difficultes_details",
        "21: Bilan du déplacement : ": "bilan",
        "22: Autres commentaires que vous voulez nous partager (liés au véhicule ou à vos besoins, envies, craintes, regard des autres, etc) ..." : "commentaires",

    }, inplace=True)
    return df

# Load 'filename' excel file into a dataframe and rename columns to usable names.
# Source file is an export of answers to the "Carnet de bord" questionnaire (filled after each professional trip)
def process_carnet_pro_file(filename):
    df_pro = pd.read_excel(filename, dtype={"Date": str, "5: La date du déplacement :": str})

    df_pro.rename(columns={
        "Date": "date_questionnaire",
        "1: Votre territoire d'expérimentation :": "territoire",
        "2: Votre NOM": "nom",
        "3: Votre prénom": "prenom",
        "4: Quel véhicule avez-vous utilisé ? ": "vehicule",
        "5: La date du déplacement :": "date",
        "6: L'heure de début d'utilisation du véhicule (environ) :": "heure_debut",
        "7: L'heure de fin d'utilisation du véhicule (environ) : ": "heure_fin",
        "8: Durée du déplacement (en minutes)": "duree",
        "9: Moment de la journée :": "moment",
        "10: Ensoleillé ": "meteo_ensoleille",
        "10: Nuageux": "meteo_nuageux",
        "10: Pluvieux": "meteo_pluvieux",
        "10: Venteux": "meteo_venteux",
        "10: Neigeux": "meteo_neigeux",
        "10: Brouillard": "meteo_brouillard",
        "10: Autre": "meteo_autre",
        "11.1: Point de départ et d'arrivée de votre déplacement :: Départ :": "depart",
        "11.2: Point de départ et d'arrivée de votre déplacement :: Arrivée :": "arrivee",
        "11.3: Point de départ et d'arrivée de votre déplacement :: Point d'étape (facultatif) :": "etape",
        "12: Estimation du nombre total de km parcourus dans le trajet": "distance",
        "13: Nombre de passagers total (conducteur inclus)": "passagers",
        "14: Motif du trajet pro": "motif",
        "15: Aucun": "avantage_aucun",
        "15: Sentiment de vitesse agréable et d'agilité à se déplacer": "avantage_agilite",
        "15: Confort du véhicule ": "avantage_confort",
        "15: Observation du paysage et des alentours": "avantage_observation",
        "15: Sentiment de fierté": "avantage_fierté",
        "15: Réactions positives des autres usagers vis à vis du véhicule ": "avantage_reactions",
        "15: Bien être physique ": "avantage_bien_etre",
        "15: Autre": "avantage_autre",
        "16: Aucune ": "difficulte_aucune",
        "16: Visibilité réduite": "difficulte_visibilite",
        "16: Aménagements": "difficulte_amenagement",
        "16: Stationnement": "difficulte_stationnement",
        "16: Problèmes avec le véhicule": "difficulte_vehicule",
        "16: Comportement des autres usagers de la route": "difficulte_comportement",
        "16: Autre": "difficulte_autre",
        "17.1: Pourriez-vous indiquer deux points sur votre trajet où vous aviez rencontré ces difficultés ? (donner l'adresse): Point noir 1 :": "point_noir_1",
        "17.2: Pourriez-vous indiquer deux points sur votre trajet où vous aviez rencontré ces difficultés ? (donner l'adresse): Point noir 2 : ": "point_noir_2",
        # "18: Aménagements cyclables": "",
        # "18: Grandes rues / boulevards en agglomération ": "",
        # "18: Petites rues en agglomération ": ""
        # "18: Grandes routes de campagne": "",
        # "18: Petites routes de campagne'": "",
        # "18: Rocades '": ""
        # "18: Autre": "",
        "19: Bilan du déplacement : ": "bilan",
        "20: Autres commentaires que vous voulez nous partager ...": "commentaires",
    }, inplace=True)

    return df_pro

# Load 'filename' excel file into a dataframe and rename columns to usable names. Also extracts the usual mode of transportation.
# Source file is an export of answers to the questionnaire "Questionnaire1" (filled before the experiment starts)
def process_profiles_file(filename):
    df_profiles = pd.read_excel(filename)
    df_profiles["prenom_lower"] = df_profiles["2: Votre Prénom : "].str.lower()
    df_profiles["nom_lower"] = df_profiles["1: Votre Nom : "].str.lower()
    mode_match = {
        '12: Voiture': "voiture",
        '12: Moto': "moto",
        '12: Vélo': "velo",
        '12: Vélo à assistance électrique': "VAE",
        '12: Trottinette électrique': "trottinette",
        '12: Marche': "marche",
        '12: Autocar / Bus': "bus",
        '12: Train Express Régional (TER)': "ter",
        '12: Autre': "autre",
        '13: Voiture': "voiture",
        '13: Moto': "moto",
        '13: Vélo': "velo",
        '13: Vélo à assistance électrique': "VAE",
        '13: Trottinette électrique': "trottinette",
        '13: Marche': "marche",
        '13: Autocar / Bus': "bus",
        '13: Train Express Régional (TER)': "ter",
        '13: Autre': "autre",
        '19: Voiture': "voiture",
        '19: Moto': "moto",
        '19: Vélo': "velo",
        '19: Vélo à assistance électrique': "VAE",
        '19: Trottinette électrique': "trottinette",
        '19: Marche': "marche",
        '19: Autocar / Bus': "bus",
        '19: Train Express Régional (TER)': "ter",
        '19: Autre': "autre",
    }
    def get_modes_domicile_travail(row):
        return ','.join([mode_match[mode] for mode in ['12: Voiture', '12: Moto', '12: Vélo', '12: Vélo à assistance électrique', '12: Trottinette électrique', '12: Marche', '12: Autocar / Bus', '12: Train Express Régional (TER)', '12: Autre'] if row[mode] == 1])
    df_profiles["mode_domicile_travail"] = df_profiles.apply(get_modes_domicile_travail, axis=1)
    def get_modes_domicile_etudes(row):
        return ','.join([mode_match[mode] for mode in ['13: Voiture', '13: Moto', '13: Vélo', '13: Vélo à assistance électrique', '13: Trottinette électrique', '13: Marche', '13: Autocar / Bus', '13: Train Express Régional (TER)', '13: Autre'] if row[mode] == 1])
    df_profiles["mode_domicile_etudes"] = df_profiles.apply(get_modes_domicile_etudes, axis=1)
    def get_modes_domicile_loisirs(row):
        return ','.join([mode_match[mode] for mode in ['19: Voiture', '19: Moto', '19: Vélo', '19: Vélo à assistance électrique', '19: Trottinette électrique', '19: Marche', '19: Autocar / Bus', '19: Train Express Régional (TER)', '19: Autre'] if row[mode] == 1])
    df_profiles["mode_domicile_loisirs"] = df_profiles.apply(get_modes_domicile_loisirs, axis=1)

    return df_profiles[["prenom_lower", "nom_lower", "mode_domicile_travail", "mode_domicile_etudes", "mode_domicile_loisirs"]]

# "Point noirs" are hard-coded significant locations. This method converts the text description of the location into coordinates.
# Adding a new location requires finding the text in the survey answers, and manually figuring out the corresponding coordinates.
def add_point_noir_coords(df):
    point_noir_coords_map = {
        'petite route des crotasses entre St Mathieu et Valfaunes non goudronnée sur 100 m': [43.7808682,3.8681462],
        "Dos d'âne sur la rue des avants": [43.7648089,3.8705934],
        "Rue Hector Berlioz, 34270 Saint Mathieu de Treviers (impossible de passer avec le véhicule)": [43.7669002,3.8682666],
        "Piste au départ de saint Mathieu de Treviers vers valflaunes (j'ai fait demi tour pour utiliser la route des voitures car trop de trous/cailloux)": [43.7752767,3.8693652],
        "D17 : parfois pas assez d'espace pour que les voitures me doublent": [43.7767534,3.8706428],
        "lorsque je circule sur des boulevards avec beaucoup de circulation. les rétroviseurs sont petits, c'est probablement une manque d'habitude par rapport à ceux bien plus grand des voitures" : [44.0900447,3.0678103],
        "275 rue de la cadenède 12100 Millau": [44.1034102,3.0502146],
        "montée très difficile - (rue charles dutheil Millau)": [44.0945507,3.0677134],
        "BD Georges Brassens 12100 Millau": [44.115148,3.0716997],
        "avenue charles de gaulle - montée conséquente - dans la partie la plus pentue, impossible d'aller à plus de 10km/h, ce qui rend la présence sur la route assez dangereuse.": [44.1101351,3.0724243],
        "Route D17": [43.7767524,3.8706418],
        "D17": [43.7767544,3.8706448],
        "rue des aumières - la montée est conséquente, et le véhicule est vraiment difficile à faire monter, meme en mode turbo, alors que j'étais seul": [44.1074885,3.0555594],
        "Rue de la Mairie à saint Clément de Rivière (montée)": [43.683914,3.8472607],
        "au stop Rue du Ravin d'Embarre à saint Clément de Rivière (montée)": [43.6937266,3.8499302],
        "Montée": [43.7313083,3.8114369],
        "Trottoir sans rigole pour descendre": [43.7313083,3.8114369],
        "boulevard Richard": [44.0959121,3.0786359],
        "la capelle": [44.1001077,3.0811205],
        "place de la capelle": [44.1001077,3.0811205],
        "portion 110km/h entre Millau et Aguessac": [44.1309073,3.0983885],
        "portion 110km/h autre rive": [44.1309073,3.0983885],
        "chaucidou de Paulhe" : [44.1129669,3.0863373],
        "tous les virages serrés ou il n'y a pas de visibilité : cela ressemble à une voiture, les autres voitures arrivent donc trop vites malgrès le logo 45km/h. Je me sens plus à l'aise en vélo à 45km/h.": [44.1164802,3.2114564],
        "montés : le véhicule plaffone entre 28 et 33km/h : nécessité de se mettre sur le bas côté pour laisser passer les autres véhicules qui roulent à 60km/h": [44.1164802,3.2114564],
        "Stationnement sur le lieu travail non couvert": [44.0978341,3.080611],
        "Stop 115 av jean jaures": [44.1091175,3.0813238],
        "Hors agglomération" : [44.1152373,3.1755387],
        "Véhicule qui double, route rurale": [44.1152373,3.1755387],
        "Le Karbike a du mal à monter les pentes un peu raide": [44.1138758,3.0799804],
        "Manque d'assistance électrique en montée": [44.1396008,3.1047633],
        "Barrière bois voie verte": [46.535765,4.6827269],
        "Peu de pistes cyclables dédiées sur l'ensemble du parcours": [43.6730181,3.7998057],
        "Pont de cureplat : obligation d'être sur la route mais les voiture ne le savent pas": [44.101914,3.0862243],
        "Ralentisseur dans  Prades le lez": [43.7025603,3.8648561],
        "Bouches d'égout et raccords de bitume Prades": [43.7025603,3.8648561],
        'https://www.openstreetmap.org/search?lat=46.418038&lon=4.688416#map=17/46.418038/4.688416': [46.418038,4.688416],
        'Sortie des Matelles pour accès route à 90km/h': [43.7242529,3.7950335],
        'Sortie de St Martin de Londres': [43.7803655,3.7373324],
        'Certaines pistes cyclable bidirectionnelles sont trop étroites (43.639712, 3.927907)': [43.639712,3.927907],
        'Rond points': [43.7303041,3.8693263],
        'rue de la Croix Vielle': [44.0989672,3.0645362],
        'Parking la poste cluny': [46.4330267,4.6637459],
        'Voie verte - chicanes': [46.5357473,4.6828578],
        'gros rond point': [43.773931,3.8694551],
        "dos d'ane": [43.7725399,3.8690966],
        "Vitesse limitée en côte": [43.8546179,3.7421585],
        "Rond point au croisement de la rue des avants et av de Montpellier": [43.7658837,3.8662699],
        "Intermarché": [43.7606147,3.8664841],
        "D17 : super quand l'accotement permet de rouler hors de la route pour laisser les voitures doubler, compliqué sinon car on gène les voitures": [43.7767524,3.8706408],
        "au Stop Chemin du Grand Devois à saint Clément de Rivière à l'intersection du Boulevard des sources": [43.6871345,3.8444706],
        "montés : le véhicule plaffone entre 28 et 33km/h : nécessité de se mettre sur le bas côté pour laisser passer les autres véhicules qui roulent à 60km/h": [44.1181525,3.2176943],
        "https://www.openstreetmap.org/search?lat=46.387879&lon=4.705212#map=18/46.387879/4.705212": [46.387879, 4.705212],
        "Dur la départementale": [46.5122572,4.6030092],
        "Fragile sur la rouge avec grand vent": [46.5752257,4.5383397],
        "Rue des chataigniers, Saint saturnin": [48.0624038,0.1673337],
        "Rue du mans, la milesse" : [48.0616425,0.1397762],
        "Le cormier, Saint saturnin" :[48.0537238,0.1608495],
        "Avenue de l'Abbé Paul Parguel, Montpellier (travaux sur la piste cyclable avec voie très étroite et pierres sur la piste)": [43.6361417,3.8598567]
    }

    def get_lat(point_noir):
        if point_noir not in point_noir_coords_map:
            return None
        return point_noir_coords_map[point_noir][0]

    def get_lon(point_noir):
        if point_noir not in point_noir_coords_map:
            return None
        return point_noir_coords_map[point_noir][1]

    df["point_noir_1_lon"] = df.point_noir_1.apply(get_lon)
    df["point_noir_1_lat"] = df.point_noir_1.apply(get_lat)
    return df

# Most users do not fill the surveys with the exact same territory names. This methods unifies that.
# It requires frequent updates if new territories are added or when respondant use a new spelling (highlighted as "unknown territory" in the logs)
def fix_territories_names(df):
    territoires_mapping = {
        'Les Mureaux': 'Commune des Mureaux',
        'CC Clunissois': 'CC Clunisois', 
        'CC de Puisayes Forterre': 'CC de Puisayes Forterre',
        'CC de Puisaye-Forterre': 'CC de Puisayes Forterre',
        'CC Grand Pic Saint Loup': 'CC Grand Pic St Loup',
        'Le Teil': 'Commune du Teil', 
        'PNR Grands Causses': 'PNR Grand Causses', 
        'Millau': 'PNR Grand Causses', 
        'Cluny 71250': 'CC Clunisois',
        'Loos-en-Gohelle': 'Loos en Gohelle', 
        'Le mans': "Le Mans",
        "Le Mans Métropole": "Le Mans",
        "CC des 7 Vallées": "CC 7 Vallées",
        "SM de l'Avant Pays Savoyard": "Avant Pays Savoyard",
        "CA du Grand Avignon": "CA du Grand Avignon",
        "La Chapelle-Thouarault": "La Chapelle-Thouarault",
        "Centre Hospitalier de Niort": "Centre Hospitalier de Niort",
        "CC Briançon": "CC Briançon",
        "CC du Briançonnais": "CC Briançon",
        "Toulouse": "Toulouse",
        "haute vallée cevenoles": "PNR Grand Causses",
        "Chalap": "PNR Grand Causses",
        "Sénéchas": "PNR Grand Causses",
        "Bassin d’alès": "PNR Grand Causses",
        "Bassin alésien": "PNR Grand Causses",
        "sorean": "PNR Grand Causses",
        "National": "PNR Grand Causses",
        "PETR Sud Lozère": "PETR Sud Lozère",
    }
    # set territoire to Toulouse if territoire includes "INSA"
    df.loc[df['territoire'].str.contains('INSA'), 'territoire'] = 'Toulouse'
    def map_fn(x):
        if x in territoires_mapping:
            return territoires_mapping[x]
        print(f"Unknown territory: {x}")
        return None
    df['territoire'] = df['territoire'].map(map_fn)
    return df

# Most users do not fill the surveys with the exact same vehicule names. This methods unifies that.
# It requires frequent updates if new vehicules are added or when respondant use a new spelling (highlighted as "unknown vehicule" in the logs)
def fix_vehicules_names(df):
    vehicule_mapping = {
        'Acticycle': "Acticycle",
        'Bagnole': "La Bagnole",
        "BAGNOLE": "La Bagnole",
        "KILOW BAGNOLE": "La Bagnole",
        'Biro': "BIRO",
        'Citroën AMI': "AMI",
        'Formidable': "Formidable",
        'Galian': "Formidable",
        # 'Golf 6': "Golf6",
        'Karbikes': "Karbikes",
        'LA BAGNOLE': "La Bagnole",
        "La bagnole": "La Bagnole",
        "Kilow la bagnole": "La Bagnole",
        "La Bagnole": "La Bagnole",
        'Midi pile': "Midipile",
        'midipile 09h23': "Midipile",
        'midipile': "Midipile",
        'Podbike': "Frikar",
        'QBX Sorean': "Sorean",
        'QBX SOREAN': "Sorean",
        'Soréan QBX': "Sorean",
        'Sorean': 'Sorean',
        'sorean': "Sorean",
        'SOREAN/BESTIOLE': "Sorean",
        'Soreano': 'Sorean',
        'Sorean qbx': 'Sorean',
        'Qbx Sorean': 'Sorean',
        'Speedbike': "Speedbike",
        'Urbaner': "Urbaner",
        'Vhélio': "Vhelio",
        'Weez': "WEEZ",
        "9h23 midipile": "Midipile",
        "Bestiole - qbx": "Sorean",
        "Bestiole": "Sorean",
        "Cyclospace": "Cyclospace",
        "Maillon Mobility": "Maillon Mobility",
        "Maillon": "Maillon Mobility",
        "Midipile": "Midipile",
        "BOB": "BOB",
        "Galibot": "Galibot",
        "Woodybus": "Woodybus",
    }
    def map_fn(x):
        if x in vehicule_mapping:
            return vehicule_mapping[x]
        print(f"Unknown vehicule: {x}")
        return None
    df['vehicule'] = df['vehicule'].map(map_fn)
    return df

# Support different date and hours formats, creates start_time and end_time columns with datetime objects
def fix_dates(df):
    df["heure_debut"] = df["heure_debut"].apply(lambda x: x if x != "99:99" else "00:00")
    df["heure_fin"] = df["heure_fin"].apply(lambda x: x if ((x != "99:99") & (x != "24:00") & (x != "00:00")) else "23:59")

    # Strip anything after the day info
    def strip_date(x):
        try:
            return x.split(" ")[0]
        except:
            return x
    df["date"] = df["date"].apply(strip_date)

    def compute_datetime(raw_time):
        if "/" in raw_time:
            return datetime.datetime.strptime(raw_time, "%m/%d/%Y %H:%M").replace(tzinfo=ZoneInfo("Europe/Paris"))
        return datetime.datetime.strptime(raw_time, "%Y-%m-%d %H:%M").replace(tzinfo=ZoneInfo("Europe/Paris"))

    df["start_time"] = df.date + ' ' + df.heure_debut
    df = df[df.start_time.notnull()]
    df.start_time = df.start_time.apply(compute_datetime)

    df["end_time"] = df.date + ' ' + df.heure_fin
    df = df[df.end_time.notnull()]
    df.end_time = df.end_time.apply(compute_datetime)

    df["date"] = df["start_time"].dt.strftime("%Y-%m-%d")

    return df

# Since survey results always contain all the previous answers, we only have to load the latest one
# This is done by sorting files by name, since they include a timestamp, and fetch the first one matching a keyword
def find_latest_file(filenames, filename_keyword):
    for filename in filenames:
        if filename_keyword in filename:
            return filename
    return None

def process_carnet(df_trips):
    filenames = os.listdir(SURVEY_SOURCES_FOLDER)
    filenames = sorted(filenames, reverse=True)

    df_carnet = process_carnet_file(f"{SURVEY_SOURCES_FOLDER}/{find_latest_file(filenames, 'Carnetdebord-')}")
    df_pro = process_carnet_pro_file(f"{SURVEY_SOURCES_FOLDER}/{find_latest_file(filenames, 'CarnetdebordPRO')}")
    df_tourisme = process_tourisme_file(f"{SURVEY_SOURCES_FOLDER}/{find_latest_file(filenames, 'Retourd')}")
    df_profiles = process_profiles_file(f"{SURVEY_SOURCES_FOLDER}/{find_latest_file(filenames, 'Questionnaire1')}")
    df_niort = pd.read_csv(f"{SURVEY_SOURCES_FOLDER}/carnet_niort_formated.csv", sep=';')
    df_le_mans = process_carnet_pro_file(f"{SURVEY_SOURCES_FOLDER}/Le_Mans_Carnet de bord PRO.xlsx")

    df = pd.concat([df_carnet, df_pro, df_tourisme, df_niort, df_le_mans], ignore_index=True)

    df = fix_territories_names(df)
    df = fix_vehicules_names(df)
    df = fix_dates(df)
    # trim bilan, to avoid trailing spaces
    df["bilan"] = df["bilan"].str.strip()

    df["carnetEntryIndex"] = df.index

    df["prenom_lower"] = df["prenom"].str.lower()
    df["nom_lower"] = df["nom"].str.lower()

    # Merge with profiles information (helps knowing the respondant usual mode of transportation)
    df_with_profiles = df.merge(df_profiles, left_on=["prenom_lower", "nom_lower"], right_on=["prenom_lower", "nom_lower"], how="left")

    # Find matching GPS trips
    one_hour_delta = datetime.timedelta(hours=1)
    def find_carnet_entry_index(row):
        res = df_with_profiles[
            (df_with_profiles.territoire == row.location) & 
            (df_with_profiles.vehicule == row.Model) & 
            # Tstart in [Cstart-1:Cend+1] or Tend in [Cstart-1:Cend+1]
            (((row['StartTime'] >= df_with_profiles.start_time - one_hour_delta) & (row["StartTime"] <= df_with_profiles.end_time + one_hour_delta)) |
            ((row['EndTime'] >= df_with_profiles.start_time - one_hour_delta) & (row["EndTime"] <= df_with_profiles.end_time + one_hour_delta)))
        ]
        if res.empty:
            return None
        return res.carnetEntryIndex.iloc[0]
    for index, row in df_trips.iterrows():
        carnetEntryIndex = find_carnet_entry_index(row)
        df_trips.loc[index, 'carnetEntryIndex'] = carnetEntryIndex

    trips_with_carnet_match = df_trips.merge(df_with_profiles, on="carnetEntryIndex", how="outer")

    trips_with_carnet_match = add_point_noir_coords(trips_with_carnet_match)

    return trips_with_carnet_match