import pandas as pd
import numpy as np
import datetime
from zoneinfo import ZoneInfo
import os

'''
This file contains methods to process the raw data from various questionnaires sent to users.

Most of the methods are used to clean survey data, fixing typos and inconsistencies.

After cleanup, the survey replies are also matched to GPS trip data generated by the process_gps_data.py script.
    Matching is done by comparing declared location, vehicule type and date of the trip to the extracted trip data.
    A large margin of error is allowed, since trip detection is not perfect, and respondants aren't always accurate in dating their trips.

Sources:
    SURVEY_SOURCES_FOLDER/Carnetdebord-[...].xlsx : excel file containing answers to the "Carnet de bord" questionnaire (filled after each trip)
    SURVEY_SOURCES_FOLDER/CarnetdebordPRO[...].xlsx : excel file containing answers to the "Carnet de bord" questionnaire (filled after each professional trip)
    SURVEY_SOURCES_FOLDER/Retourd[...].xlsx : excel file containing answers to the tourism questionnaire (filled after each tourism tryout)
    SURVEY_SOURCES_FOLDER/Questionnaire1[...].xlsx : excel file containing answers to the initial questionnaire (filled before the experiment starts)
    SURVEY_SOURCES_FOLDER/Le_Mans_Carnet de bord PRO.xlsx : excel file containing answers to a "Carnet de bord" questionnaire specific to Le Mans
    ../carnet_niort_formated.csv : csv file containing answers to a "Carnet de bord" questionnaire specific to Niort Hospital

Param:
    df_trips : dataframe containing trip data, with one row per trip. It was generated using the process_gps_data.py script.
        It contains the following columns:
            'UniqueTripID', 'coords', 'timestamps', 'TotalDistanceKm', 'AvgSpeed',
            'StartTime', 'EndTime', 'Licence plate', 'VIN', 'vehicle ID', 'Brand',
            'Model', 'Category', 'External temperature (°C)', 'T° Sensor 1',
            'Prev datetime', 'DurationSinceLast', 'location'

Returns:
    trips_with_carnet_match : df_trips dataframe extended with information extracted from the surveys.
        One row still corresponds to one trip, with the exception of survey results that could not be matched. 
        In that case, the new columns corresponding to survey results are filled, and trip columns are set to None.
        When a match is found, both the trip and the survey columns are filled.
        Columns added to the existing df_trips columns (subset of used columns, the dataframe includes every column from the original survey files):
            "carnetEntryIndex", "date_questionnaire", "territoire", "nom", "prenom", "vehicule", 
            "date", "heure_debut", "heure_fin", "duree", "moment", 
            "meteo_ensoleille", "meteo_nuageux", "meteo_pluvieux", "meteo_venteux", "meteo_neigeux", "meteo_brouillard", "meteo_autre", 
            "depart", "arrivee", "etape", "distance", "passagers", 
            "avantage_aucun", "avantage_agilite", "avantage_confort", "avantage_observation", "avantage_fierté", "avantage_reactions", "avantage_bien_etre", "avantage_autre", 
            "difficulte_aucune", "difficulte_visibilite", "difficulte_amenagement", "difficulte_stationnement", "difficulte_vehicule", "difficulte_comportement", "difficulte_autre", "difficultes_details"
            "point_noir_1", "point_noir_2", "bilan", "commentaires", 
            "tourisme_avantages_detail", "tourisme_difficulte_trafic", "tourisme_difficulte_meteo", "tourisme_difficulte_denivele", 
            "tourisme_difficulte_distance", "tourisme_difficulte_autonomie", "tourisme_difficulte_diff_vitesse", "tourisme_difficulte_positionnement", 
            "tourisme_difficulte_intersection", "tourisme_difficulte_depart_cote", "tourisme_difficulte_fatigue", "tourisme_difficulte_depassement", 
            "tourisme_difficulte_autre", "tourisme_difficulte_detail",
            "start_time", "end_time", "prenom_lower", "nom_lower", "mode_domicile_travail", "mode_domicile_etudes", "mode_domicile_loisirs", 
            "point_noir_1_lon", "point_noir_1_lat", 
'''

# Support different date and hours formats, creates start_time and end_time columns with datetime objects
def fix_dates(df):
    df["heure_debut"] = df["heure_debut"].apply(lambda x: x if x != "99:99" else "00:00")
    df["heure_fin"] = df["heure_fin"].apply(lambda x: x if ((x != "99:99") & (x != "24:00") & (x != "00:00")) else "23:59")

    # Strip anything after the day info
    def strip_date(x):
        try:
            return x.split(" ")[0]
        except:
            return x
    df["date"] = df["date"].apply(strip_date)

    def compute_datetime(raw_time):
        if "/" in raw_time:
            return datetime.datetime.strptime(raw_time, "%m/%d/%Y %H:%M").replace(tzinfo=ZoneInfo("Europe/Paris"))
        return datetime.datetime.strptime(raw_time, "%Y-%m-%d %H:%M").replace(tzinfo=ZoneInfo("Europe/Paris"))

    df["start_time"] = df.date + ' ' + df.heure_debut
    df = df[df.start_time.notnull()]
    df.start_time = df.start_time.apply(compute_datetime)

    df["end_time"] = df.date + ' ' + df.heure_fin
    df = df[df.end_time.notnull()]
    df.end_time = df.end_time.apply(compute_datetime)

    df["date"] = df["start_time"].dt.strftime("%Y-%m-%d")

    return df

def process_carnet(df_trips):
    df_survey = pd.read_csv(os.getenv("SURVEY_OUTPUT_CSV_FILE"), sep=";")

    df_survey = fix_dates(df_survey)

    df_survey["carnetEntryIndex"] = df_survey.index

    # Find matching GPS trips
    one_hour_delta = datetime.timedelta(hours=1)
    def find_carnet_entry_index(trip_row):
        res = df_survey[
            (df_survey.plate == trip_row["Licence plate"]) & 
            # Tstart in [Cstart-1:Cend+1] or Tend in [Cstart-1:Cend+1]
            (((trip_row['StartTime'] >= df_survey.start_time - one_hour_delta) & (trip_row["StartTime"] <= df_survey.end_time + one_hour_delta)) |
            ((trip_row['EndTime'] >= df_survey.start_time - one_hour_delta) & (trip_row["EndTime"] <= df_survey.end_time + one_hour_delta)))
        ]
        if res.empty:
            return None
        return res.carnetEntryIndex.iloc[0]
    
    df_trips['carnetEntryIndex'] = pd.Series(dtype='int')
    for index, trip_row in df_trips.iterrows():
        carnetEntryIndex = find_carnet_entry_index(trip_row)
        if carnetEntryIndex is not None:
            df_trips.loc[index, 'carnetEntryIndex'] = carnetEntryIndex

    trips_with_carnet_match = df_trips.merge(df_survey, on="carnetEntryIndex", how="outer")

    return trips_with_carnet_match